# Generated by Django 5.2.6 on 2025-09-25 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('qty', models.FloatField(default=0.0)),
                ('avg', models.FloatField(default=0.0)),
                ('grid_step', models.FloatField(default=0.6)),
                ('levels_up', models.IntegerField(default=8)),
                ('levels_down', models.IntegerField(default=8)),
                ('stop_from_avg', models.FloatField(default=8.0)),
                ('interval', models.IntegerField(default=15)),
                ('telegram_enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='BotState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('running', models.BooleanField(default=False)),
                ('ref_price', models.FloatField(blank=True, null=True)),
                ('trailing_high', models.FloatField(blank=True, null=True)),
                ('last_level_idx', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
