# Generated by Django 5.2.6 on 2025-09-25 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gridbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kind', models.CharField(max_length=32)),
                ('message', models.TextField()),
                ('price', models.FloatField(blank=True, null=True)),
                ('pnl_pct', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='botstate',
            name='last_kind',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='botstate',
            name='last_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='botstate',
            name='last_pnl_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='botstate',
            name='last_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
