# Generated by Django 5.2.6 on 2025-09-25 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gridbot', '0002_botsignal_botstate_last_kind_botstate_last_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='botconfig',
            name='atr_interval',
            field=models.CharField(default='1m', max_length=8),
        ),
        migrations.AddField(
            model_name='botconfig',
            name='atr_k_grid',
            field=models.FloatField(default=0.6),
        ),
        migrations.AddField(
            model_name='botconfig',
            name='atr_len',
            field=models.IntegerField(default=14),
        ),
        migrations.AddField(
            model_name='botconfig',
            name='atr_n_stop',
            field=models.FloatField(default=3.0),
        ),
        migrations.AddField(
            model_name='botconfig',
            name='atr_refresh_sec',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='botconfig',
            name='use_atr',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='botstate',
            name='atr',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='botstate',
            name='atr_trailing_stop',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='botstate',
            name='eff_grid_step',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
